# Generated by Django 3.2.5 on 2021-07-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoary', models.CharField(choices=[('CPLUS', 'C++'), ('PYTHN', 'Python'), ('REACT', 'React'), ('MONGO', 'MongoDB'), ('JAVAS', 'JavaScript')], max_length=5)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
