# Generated by Django 3.2.5 on 2021-07-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoary',
            new_name='category',
        ),
    ]
